{% set version = "8.0.2" %}

package:
  name: valkey-server
  version: {{ version }}

source:
  url: https://github.com/valkey-io/valkey/archive/refs/tags/{{ version }}.tar.gz
  sha256: e052c45b3cbe512e24fdfdc3fd337f9f5e4b8f8b8713f349ba867b829c8ff11a

build:
  number: 0
  skip: true  # [win]
  script:
    - make install -j${CPU_COUNT}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  run_constrained:
    # conflict with redis-server
    - redis-server <0.a0

test:
  commands:
    - valkey-cli --version
    - valkey-server --version
    - redis-cli --version
    - redis-server --version

about:
  home: https://valkey.io
  dev_url: https://github.com/valkey-io/valkey
  summary: A flexible distributed key-value datastore that supports both caching and beyond caching workloads.
  description: |
    Valkey is a high-performance data structure server that primarily serves
    key/value workloads. It supports a wide range of native structures and an
    extensible plugin system for adding new data structures and access patterns.
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - wolfv
