context:
  version: "8.1.3"

package:
  name: valkey-server
  version: ${{ version }}

source:
  url: https://github.com/valkey-io/valkey/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8f862b3b0a72fd40587793964539589f6f83d01361ca1598b370cfaa301e0ec0

build:
  number: 2
  skip: win
  script:
    - make install -j${CPU_COUNT} BUILD_TLS=yes

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - openssl

  run_constraints:
    # conflict with redis-server
    - redis-server <0.a0

tests:
  - script:
      - valkey-cli --version
      - valkey-server --version
      - redis-cli --version
      - redis-server --version

about:
  homepage: https://valkey.io
  repository: https://github.com/valkey-io/valkey
  summary: A flexible distributed key-value datastore that supports both caching and beyond caching workloads.
  description: |
    Valkey is a high-performance data structure server that primarily serves
    key/value workloads. It supports a wide range of native structures and an
    extensible plugin system for adding new data structures and access patterns.
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - wolfv
