context:
  version: "9.0.3"

package:
  name: valkey-server
  version: ${{ version }}

source:
  url: https://github.com/valkey-io/valkey/archive/refs/tags/${{ version }}.tar.gz
  sha256: e220f4b0143292ee6ea6d705aa40d45a0c8a77759b3e94c201cb5c25dbdca42f

build:
  number: 0
  skip: win
  script:
    - make install -j${CPU_COUNT} BUILD_TLS=yes

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - openssl

  run_constraints:
    # conflict with redis-server
    - redis-server <0.a0

tests:
  - script:
      - valkey-cli --version
      - valkey-server --version
      - redis-cli --version
      - redis-server --version

about:
  homepage: https://valkey.io
  repository: https://github.com/valkey-io/valkey
  summary: A flexible distributed key-value datastore that supports both caching and beyond caching workloads.
  description: |
    Valkey is a high-performance data structure server that primarily serves
    key/value workloads. It supports a wide range of native structures and an
    extensible plugin system for adding new data structures and access patterns.
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - wolfv
